name: Télécharger et commit le fichier PDF

on:
  push:
    branches:
      - master

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 0BMproje.tex
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: 0BMproje.pdf
          path: 0BMproje.pdf
      - name: Commit and push updated PDF
        uses: actions/git@v2
        with:
          repo: https://github.com/ikhalilatteib/computer-networks.git
          branch: master
          email: i.khalilatteib@gmail.com
          name: IBRAHIM KHALIL ATTEIB YACOUB
          message: Update PDF file
          path: 0BMproje.pdf

