name: Compile LaTeX document

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LaTeX
        uses: blang/latex-action@v1
        with:
          tex-engine: 'xelatex'
      - name: Compile LaTeX document
        run: xelatex 0BMproje.tex
      - name: Generate PDF
        run: xelatex 0BMproje.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: document.pdf
          path: document.pdf
