name: Publier le fichier PDF sur une page GitHub

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 0BMproje.tex
          pre_compile: "tlmgr update --self && tlmgr update --all"
          post_compile: "latexmk -c"
