name: Compile LaTeX document

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: vinay0410/tectonic-action@v1.1.2
        with:
          tex_path: 0BMProje.tex
          push: yes
