name: LaTeX compilation
  uses: dante-ev/latex-action@2021-A
  with:
    root_file: 0BMproje.tex
    compiler: xelatex
    args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
    extra_system_packages: biber
