name: Télécharger et commit le fichier PDF

on:
  push:
    branches:
      - master

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 0BMproje.tex
      - name: Télécharger et commit le fichier PDF
        uses: actions/create-or-update-file@v1
        with:
          # The path to the file to upload.
          # This can be a file or a directory.
          # If a directory is specified, all of its contents will be uploaded.
          path: 0BMproje.pdf
          # The name of the file on GitHub.
          # If a directory is specified in the 'path' field, this field will be ignored.
          filename: 0BMproje.pdf
          # The commit message.
          # If not specified, a default commit message will be used.
          commit_message: Ajout du fichier PDF
          # The name of the branch.
          # If not specified, the default branch will be used.
          branch: master
          # The name of the repository.
          # If not specified, the current repository will be used.
          repository: computer-networks
          # The name of the owner.
          # If not specified, the current user will be used.
          owner: ikhalilatteib

